name: Zip Creator

on:
  push:

jobs:
  create-zip:
    name: Build and Create Downloadable Zip
    runs-on: ubuntu-latest
    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Bundle files
        run: |
          mkdir -p ./temp/qbx_management
          mkdir -p ./temp/qbx_management/locales/
          cp ./{fxmanifest.lua,types.lua} ./temp/qbx_management
          cp ./{locales/en.json,locales/fr.json} ./temp/qbx_management/locales
          cp -r ./{client,config,server} ./temp/qbx_management
          cd ./temp && zip -r ../qbx_management.zip ./qbx_management

      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        with:
          automatic_release_tag: "latest"
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: 'Ready to download'
          prerelease: true
          files: qbx_management.zip
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: StarlingCityDevelopment/resources
          event-type: update-resources
